Resuelto lo de inventory Order e inventory Item
mvasquezb/LaboratoriosPUCP pull request #57
Opened 2017-06-21 04:57 UTC by faustoinfausto

Se resolvio algunos problemas menores a la hora de mostrar datos (datos incorrectos).
Se agregaron los botones para poder acceder a todas las vistas.
Django no permite la visualización de datos de un objeto seleccionado.

2017-06-21 17:11 UTC, mvasquezb requested changes
Mira

2017-06-21 17:11 UTC, mvasquezb commented on laboratorios/internal/templates/internal/inventoryOrder/create.html
> +
A qué te refieres con que Django no lo permite ?    
Qué quieres hacer, cómo estás tratando de hacerlo y qué resultados obtienes con esos intentos ?

2017-06-21 17:11 UTC, mvasquezb commented on laboratorios/internal/templates/internal/inventoryOrder/index.html
> +            </a>
Esto debería ser un botón al costado de cada solicitud, no una vista adicional

2017-06-21 17:21 UTC, faustoinfausto commented on laboratorios/internal/templates/internal/inventoryOrder/create.html
> +
Al escoger una seleccion en el combobox obtengo un pk, el django no permite usar ese pk para obtener un objeto en el html, solo en el .py

2017-06-21 17:25 UTC, faustoinfausto commented on laboratorios/internal/templates/internal/inventoryOrder/index.html
> +            </a>
Fuciono la vista de creacion de solicitudes y aprobacion de solicitudes en una sola? Osea, ya no existiria la vista de aprobar, sino los botones de aprobar y rechazar estarian al costado de visualizar, editar y eliminar.

2017-06-21 17:27 UTC, mvasquezb commented on laboratorios/internal/templates/internal/inventoryOrder/create.html
> +
No estás entendiendo cómo funciona Django, o las páginas web en general.    
Django hace procesamiento de información en el servidor, luego, usa el motor de plantillas para presentar esa información en html.    
Una vez que se presenta ese html, ni Django, ni el servidor intervienen de ninguna manera, a menos que uses ajax para solicitar información del servidor, en cuyo caso se repite el proceso.    
Entonces, si quieres hacer eso que dices, necesitas pedirle información manualmente al servidor, eso se hace con ajax.

2017-06-21 17:28 UTC, mvasquezb commented on laboratorios/internal/templates/internal/inventoryOrder/index.html
> +            </a>
Claro, serían solo botones, que llaman a un modal de confirmación. Qué más pondrías en una vista aparte ?

2017-06-21 17:33 UTC, faustoinfausto commented on laboratorios/internal/templates/internal/inventoryOrder/create.html
> +
Ok, ahora reviso ajax.

2017-06-21 17:33 UTC, faustoinfausto commented on laboratorios/internal/templates/internal/inventoryOrder/index.html
> +            </a>
Nada, era mi idea de que debian ser vistas para diferentes usuarios. Ahora lo modifico para que queden en una.

2017-06-21 17:38 UTC, mvasquezb commented on laboratorios/internal/templates/internal/inventoryOrder/index.html
> +            </a>
Como ahora vamos a incorporar el uso de roles para división y restricción de vistas, ya no sería necesario

2017-06-22 09:07 UTC, mvasquezb approved these changes
Lo voy a unir, cuando lo cambies, mandas otro pr

2017-06-22 09:07 UTC, merged